### ISSUE TITLE
`facet_wrap(scales='free')` is ignored

### ISSUE THREAD

**Issue by Inferrator** [lepennec/ggwordcloud#8]
Factors that are used for facetting aren't always balanced.
A facet for a rare category will contain very small wordcloud words. I think it would be nice if would rescale on a relative basis.

**Comment by lepennec** [comment]
Hi,

this is the expected behavior of scales="free" in ggplot2: the only scales that can be different from one facet to another are the x and the y axis.

If you want to have a size which is proportional to the groupwise proportion instead of the raw count, the best solution is to compute those proportions "manually" as in
```
df %>% count(group,word) %>% group_by(group) %>% mutate(prop = n/sum(n)) 
```
Erwan

PS: My answer is inspired by https://stackoverflow.com/questions/32207086/vary-scale-of-geom-point-size-by-facet

**Comment by Inferrator** [comment]
Thanks!
That works, of course. 
However, for teaching purposes, I try to minimize code as much as possible ... wouldn't it be possible to pass words and frequencies to `x` and `y` instead of `label`?

**Comment by lepennec** [comment]
In this case, I think that would be to hackish... The best solution would
be probably to define a stat that does that. I put this idea on my TODO
list...
